Initial commit of new intersection
senx/geoxplib pull request #2
Opened 2020-09-20 13:53 UTC by hbs

2020-09-21 12:58 UTC, ftence requested changes

2020-09-21 12:58 UTC, ftence commented on src/main/java/com/geoxp/geo/GeoXPShapeHelper.java
> +  private static long[] RESOLUTION_MASKS;
Should be `final`.

2020-09-21 12:58 UTC, ftence commented on src/main/java/com/geoxp/geo/GeoXPShapeHelper.java
> +   long[] acells = GeoXPLib.getCells(a);
Indent problem: from here there is a missing space at the beginning of each line.

2020-09-21 12:58 UTC, ftence commented on src/main/java/com/geoxp/geo/GeoXPShapeHelper.java
> +           int idx = Arrays.binarySearch(bcells, bstart[subres], bend[subres] + 1, subcell);
This signature of `Arrays.binarySearch` would require you to bump from Java 5 to Java 6.
As a result, you should update build.gradle with, for instance,
```
sourceCompatibility = 1.8
targetCompatibility = 1.8
```

2020-09-21 12:58 UTC, ftence commented on src/main/java/com/geoxp/geo/GeoXPShapeHelper.java
> +         }
Ditto.

2020-09-21 12:58 UTC, ftence commented on src/main/java/com/geoxp/geo/GeoXPShapeHelper.java
> +         }
This won't work because `aend[i] = astart[j] - 1` does not hold for `i < 8` and `j >= 8`.

2020-09-22 13:31 UTC, hbs commented
PTAL

2020-09-23 06:19 UTC, hbs commented
PTAL

2020-09-23 11:42 UTC, ftence commented
Here is a test on the intersection of blue and red shapes giving the orange result, with individual cells only displayed for the orange shape. Everything seems to work. Permutation test is also OK.
![image](https://user-images.githubusercontent.com/22769955/94007722-2b3a6d00-fda2-11ea-8b4c-71dde4347094.png)

2020-09-23 11:42 UTC, ftence approved these changes

2020-09-23 12:09 UTC, merged